package cv.edylsonf.classgram.presentation.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006974)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF87f2ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001f23)
val md_theme_light_secondary = Color(0xFF006782)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFb6eaff)
val md_theme_light_onSecondaryContainer = Color(0xFF001f29)
val md_theme_light_tertiary = Color(0xFF515e7d)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFd7e2ff)
val md_theme_light_onTertiaryContainer = Color(0xFF0d1b36)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdfd)
val md_theme_light_onBackground = Color(0xFF191c1d)
val md_theme_light_surface = Color(0xFFfbfdfd)
val md_theme_light_onSurface = Color(0xFF191c1d)
val md_theme_light_surfaceVariant = Color(0xFFdae4e5)
val md_theme_light_onSurfaceVariant = Color(0xFF3f494a)
val md_theme_light_outline = Color(0xFF6f797a)
val md_theme_light_inverseOnSurface = Color(0xFFeff1f1)
val md_theme_light_inverseSurface = Color(0xFF2e3131)

val md_theme_dark_primary = Color(0xFF47d9ea)
val md_theme_dark_onPrimary = Color(0xFF00363c)
val md_theme_dark_primaryContainer = Color(0xFF004f57)
val md_theme_dark_onPrimaryContainer = Color(0xFF87f2ff)
val md_theme_dark_secondary = Color(0xFF5fd4fd)
val md_theme_dark_onSecondary = Color(0xFF003545)
val md_theme_dark_secondaryContainer = Color(0xFF004d62)
val md_theme_dark_onSecondaryContainer = Color(0xFFb6eaff)
val md_theme_dark_tertiary = Color(0xFFb9c6ea)
val md_theme_dark_onTertiary = Color(0xFF23304c)
val md_theme_dark_tertiaryContainer = Color(0xFF394664)
val md_theme_dark_onTertiaryContainer = Color(0xFFd7e2ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1d)
val md_theme_dark_onBackground = Color(0xFFe0e3e3)
val md_theme_dark_surface = Color(0xFF191c1d)
val md_theme_dark_onSurface = Color(0xFFe0e3e3)
val md_theme_dark_surfaceVariant = Color(0xFF3f494a)
val md_theme_dark_onSurfaceVariant = Color(0xFFbfc8ca)
val md_theme_dark_outline = Color(0xFF899394)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1d)
val md_theme_dark_inverseSurface = Color(0xFFe0e3e3)

val seed = Color(0xFF62eeff)
val error = Color(0xFFba1b1b)

